name: dts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  geolocator: ^10.1.0
  google_maps_flutter: ^2.2.0
  get: ^4.6.6
  geocoding: ^2.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  font_awesome_flutter: ^10.6.0
  awesome_dialog: ^3.1.0
  cupertino_icons: ^1.0.2


  

flutter:
  uses-material-design: true
  assets:
    - assets/images/anasayfaicon.png
    - assets/images/profilicon.png
    - assets/images/anasayfaortafoto.png